= Rock Paper Scissors Lizard Spock Graph Gist =

"Rock, Paper, Scissors, Lizard, Spock" is a variation of the children's 3-way lock hand game called Rock Paper Scissors (or 'Roshambo').  The 'Lizard Spock' version of the game has been made popular by the television show "Big Bang Theory."

See also the http://en.wikipedia.org/wiki/Rock-paper-scissors-lizard-Spock[rules for the game on Wikipedia] and check out the *http://www.youtube.com/watch?v=cSLeBKT7-sM[YouTube video]*!

== Getting Started
//console
//hidden
//setup

Use the statement below to populate the graph with the objects and relationships.
[source,cypher]
----
CREATE p=(paper:object {name:"paper"})-[:covers]->(rock:object {name:"rock"})-[:crushes]->(scissors:object {name:"scissors"})-[:decapitates]->(lizard:animal {name:"lizard"})-[:poisons]->(spock:vulcan:person {name:"spock"})-[:vaporizes]->(rock)-[:crushes]->(lizard)-[:eats]->(paper)-[:disproves]->(spock)-[:smashes]->(scissors)-[:cuts]->(paper)
----

== Wipe the database
Use the code below at any time to wipe the database and start over...
[source,cypher]
----
MATCH (n)
DETACH DELETE (n)
----

=== Find all Objects
[source,cypher]
----
match (n:object) return n
----


=== Find all non-objects
[source,cypher]
----
match n where NOT (n:object) return n
----


=== Find all vulcans
[source,cypher]
----
match (n:vulcan) return n
----

=== What are the actions for Rock?
[source,cypher]
----
MATCH (n:object{name:"rock"})-[rel]->x
return n,r,x
----


=== What are the actions for Paper?
[source,cypher]
----
MATCH (n:object{name:"paper"})-[rel]->x
return n,r,x
----


=== What are the actions for Scissors?
[source,cypher]
----
MATCH (n:object{name:"scissors"})-[rel]->x
return n,r,x
----


=== What are the actions for Lizard?

[source,cypher]
----
MATCH (n:object{name:"rock"})-[rel]->x
return n,r,x
----


=== What are the actions for Spock?

[source,cypher]
----
MATCH (n:vulcan{name:"Spock"})-[r]->x
return n,r,x
----

